spring:
  profiles: test
  datasource:
    url: jdbc:mysql://192.168.0.39:3306/stepdb_file?useUnicode=true&characterEncoding=UTF-8&amp;amp;autoReconnect=true
    username: root
    password: Qc+lVOUSHDmrG3CWleTKQ05KnUce/7QFrsowits2sLUzO2idxdn4r3UXWaYmRNxSlX4H0gMMN89hLCt6WGyejg==
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters:  config,wall
      connectionProperties: config.decrypt=true
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 30000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize:  20


accessToken: 450a38b585934a11b3cc8f10a3007163
basedir: /E://step/filedata
deletedir: /E://step/delete_file
privatedir: /E://step/private_file
